movie_module.award_winning_movie.*:
  type: config_entity
  label: Award Winning Movie
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Movie Name
    uuid:
      type: string
    description:
      type: string
    movie_year:
      type: date
      label: Movie Year
