<?php

/**
 * @file
 * Functions to support theming in the custom_theme theme.
 */

/**
 * Implements template_preprocess_html().
 */
function my_custom_theme_preprocess_html(&$variables) {
  // Check if the current node is of Movies content type.
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    if ($node->bundle() == 'movie') {
      $variables['attributes']['class'][] = 'movie-content-type';
    }
  }
}
