<?php

/**
 * Implements hook_theme().
 */
function events_db_module_theme($existing, $type, $theme, $path): array {
  return [
    'event_dashboard' => [
      'variables' => [
        'yearly_event' => NULL,
        'quarterly_event' => NULL,
        'event_type' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function events_db_module_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'events_db_module/bootstrap';
}
