<?php

/**
 * Implements hook_form_alter().
 */
function hello_world_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'hello_world_form') {
    $form['name']['#title'] = t('Hello World Form');
    $form['name']['#placeholder'] = t('This is implemented using hooks_form_alter');
    $form['actions']['submit']['#value'] = t('Save Form Now');
  }
}

/**
 * Implements hook_theme().
 */
function hello_world_theme($existing, $type, $theme, $path): array{
  return [
    'hello_world_block' => [
      'variables' => [
        'data' => [],
        'active_tab' => NULL,
        'body_text' => NULL,
        'tabs' => [],
      ],
    ],
  ];
}
