<?php

/**
 * @file
 * This file demonstrates how to use hook functions.
 */

/**
 * Implements hook_cron().
 */
function pavilion_cron() {
  \Drupal::messenger()->addMessage(t("Hello from pavilion cron hook!"));
}

/**
 * Implements hook_form_alter().
 */
function pavilion_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_article_edit_form') {
    $form['actions']['submit']['#value'] = t("Save this awesome article!");
  }
}
